# Generated by Django 5.2.14 on 2026-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_country_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(default='India', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
